version: '3.8'

services:
  db:
    image: postgres:15
    container_name: project-postgres
    restart: always
    ports:
      - "32368:5432"
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    networks:
      - project-net

  project-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - project-net

networks:
  project-net:
    driver: bridge
